name = "SP2TVis"
uuid = "4df5d85a-9921-4468-8597-6040ccd6f267"
authors = ["lanceXwq <lance.xwq@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
